### ISSUE TITLE
Calculation of G

### ISSUE THREAD

**Issue by GuitarPikstar** [rhymesg/MC_CRB_nonGaussian#1]
Hello,
The equation 15 of your paper does not fit with your realization in line 131/138 of `main_TRN_1d.m`:
The value for e.g. thetp should be 
```
            thetpp = thet + (c_tlde*Delk_tlde) + (c*Delk);
            thetp = thet - (c_tlde*Delk_tlde) + (c*Delk);
```
but in your code it is
```
            thetpp = thet + (c_tlde*Delk_tlde) + (c*Delk);
            thetp = thet + (c*Delk);
```
So I would have expected there the negative term of the perturbation. When I change this to my suggested solution, I get of course different results. Or did I missunderstood something?

Thank you

**Comment by rhymesg** [comment]
I just followed the cited work for that part (see estimateFIM.html). What I can see is that, for some reason, the original code used only the half of the perturbation and dropped division by 2 in (15) in the code. I guess the result would be similar if you put /2 in the code with the negative term of the perturbation. You can check related works (ref [5] and [8]) to see which way is mathematically correct.

**Comment by GuitarPikstar** [comment]
Thank you very much, that helped a lot.
